[ECOS-166] Fixed get_margin_bank_balance call for readonly client
fireflyprotocol/bluefin-v2-client-python pull request #44
Opened 2023-11-17 10:23 UTC by NidaKarimAli

2023-11-17 14:55 UTC, YameenMalik requested changes

2023-11-17 14:55 UTC, YameenMalik commented on src/bluefin_v2_client/client.py
> +            callArgs.append(userAddress)
userAddress or self.account.getUserAddress()

2023-11-17 14:55 UTC, YameenMalik commented on src/bluefin_v2_client/client.py
> +            callArgs.append(userAddress)
userAddress or self.account.getUserAddress()

2023-11-18 09:56 UTC, YameenMalik approved these changes

2023-11-20 07:31 UTC, anushaali-26 approved these changes

2023-11-20 08:14 UTC, merged